name: .NET CI for Emby Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'      # أو أي إصدار داعم netstandard2.0
    - name: Restore dependencies
      run: dotnet restore
    - name: Build project
      run: dotnet build --configuration Release --no-restore
    - name: Test (if any)
      run: dotnet test --no-build --verbosity normal
    - name: Publish artifact
      run: dotnet publish -c Release -o ./publish
    - name: Upload build outputs
      uses: actions/upload-artifact@v3
      with:
        name: emby-subdl-plugin
        path: publish/
